### ISSUE TITLE
Make github releases

### ISSUE THREAD

**Issue by JohnVeness** [MythTV-Themes/Mythbuntu#20]
I realise it's not needed for MythTV to pick up new versions, but it'd be nice if you could make github releases (i.e. in https://github.com/MythTV-Themes/Mythbuntu/releases) for new versions. It would make it easier for someone to download an old version of the theme, for example. Thanks!

**Comment by twitham1** [comment]
Only the latest version fixes all known bugs and is supported.  I'd rather not make it easier to run older versions and cause problems that are already fixed.  Prior to v32 there were a couple screens that didn't even work for example.

I checked other themes and almost none have releases.  Where they are, the repo has moved on and holds changes not in the last stale release.  So this would also be confusing when we forget to make them in the future.  Seems easier for the repo itself to hold all history and be the 1 source of both latest and all prior versions.

I probably should at least tag when the version changes though.  Speaking of which: any more bug fixes that should go in before we bump the version to 33.2?  This will trigger users to get the update.

**Comment by JohnVeness** [comment]
Thanks for your considered reply. Yes, I noticed most other themes also don't have github releases, and actually I think it would be good if those did too - it's just that Mythbuntu is the only theme I use, so I reported here! I don't think making github releases implies old versions have any support, no more than in any other project that makes releases. My wording was a bit misleading though - it's not really that I would like to *use* an old version, more that I would like an easier way to see what's *changed* from one version to another. If not releases, then tags would also work for that :)

I haven't noticed any other problems with the theme, thanks.

**Comment by twitham1** [comment]
Ok, I think I got some tags right:

```
> git tag -l -n
 25.1            Release 25.1, 2011/07
 26.1            Release 26.1, 2012/08
 26.20           Release 26.20, 2013/02
 28.1            Release 28.1, 2014/01
 28.10           Release 28.10, 2014/08
 28.20           Release 28.20, 2015/01
 28.21           Release 28.21, 2016/05
 30.1            Release 30.1, 2018/11
 30.2            Release 30.2, 2021/09
 32.0            Release 32.0, 2023/01
 32.1            Release 32.1, 2023/03
 33.0            Release 33.0, 2024/01
 33.1            Release 33.1, 2024/02
 33.2            Release 33.2, 2024/05
```
All versions are tagged since 30.1 and a good selection prior and the descriptions include the year/month.  Here on github, it appears you can click any tag and get that "release" generated on the fly.  But I still prefer a git clone so you can see all the logs and diffs easily.  And now with the tags you can say things like:

`git diff 33.1 33.2`

Thanks for the great idea!

**Comment by JohnVeness** [comment]
Woohoo, thanks very much, that's perfect :)
